package org.orisland.wows.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.orisland.wows.db.entity.PlayerData;
import org.orisland.wows.db.entity.PlayerDataExample;

public interface PlayerDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_data
     *
     * @mbg.generated
     */
    long countByExample(PlayerDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_data
     *
     * @mbg.generated
     */
    int deleteByExample(PlayerDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_data
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long qqNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_data
     *
     * @mbg.generated
     */
    int insert(PlayerData row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_data
     *
     * @mbg.generated
     */
    int insertSelective(PlayerData row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_data
     *
     * @mbg.generated
     */
    List<PlayerData> selectByExampleWithBLOBs(PlayerDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_data
     *
     * @mbg.generated
     */
    List<PlayerData> selectByExample(PlayerDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_data
     *
     * @mbg.generated
     */
    PlayerData selectByPrimaryKey(Long qqNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_data
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") PlayerData row, @Param("example") PlayerDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_data
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") PlayerData row, @Param("example") PlayerDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_data
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") PlayerData row, @Param("example") PlayerDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PlayerData row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(PlayerData row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PlayerData row);
}