package org.orisland.wows.db.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table player_data
 */
public class PlayerData {
    /**
     * Database Column Remarks:
     *   qq号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_data.qq_number
     *
     * @mbg.generated
     */
    private Long qqNumber;

    /**
     * Database Column Remarks:
     *   区服eu/ru/na/asia
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_data.server
     *
     * @mbg.generated
     */
    private String server;

    /**
     * Database Column Remarks:
     *   窝窝屎id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_data.account_id
     *
     * @mbg.generated
     */
    private Long accountId;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_data.date
     *
     * @mbg.generated
     */
    private Date date;

    /**
     * Database Column Remarks:
     *   战绩
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_data.ship_data
     *
     * @mbg.generated
     */
    private String shipData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_data.qq_number
     *
     * @return the value of player_data.qq_number
     *
     * @mbg.generated
     */
    public Long getQqNumber() {
        return qqNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_data.qq_number
     *
     * @param qqNumber the value for player_data.qq_number
     *
     * @mbg.generated
     */
    public void setQqNumber(Long qqNumber) {
        this.qqNumber = qqNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_data.server
     *
     * @return the value of player_data.server
     *
     * @mbg.generated
     */
    public String getServer() {
        return server;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_data.server
     *
     * @param server the value for player_data.server
     *
     * @mbg.generated
     */
    public void setServer(String server) {
        this.server = server == null ? null : server.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_data.account_id
     *
     * @return the value of player_data.account_id
     *
     * @mbg.generated
     */
    public Long getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_data.account_id
     *
     * @param accountId the value for player_data.account_id
     *
     * @mbg.generated
     */
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_data.date
     *
     * @return the value of player_data.date
     *
     * @mbg.generated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_data.date
     *
     * @param date the value for player_data.date
     *
     * @mbg.generated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_data.ship_data
     *
     * @return the value of player_data.ship_data
     *
     * @mbg.generated
     */
    public String getShipData() {
        return shipData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_data.ship_data
     *
     * @param shipData the value for player_data.ship_data
     *
     * @mbg.generated
     */
    public void setShipData(String shipData) {
        this.shipData = shipData == null ? null : shipData.trim();
    }
}